local ReplicatedStorage = game:GetService('ReplicatedStorage')
local RunService = game:GetService('RunService')
local LocalPlayer = game:GetService('Players').LocalPlayer

LocalPlayer.Name = ''


RunService.Heartbeat:Connect(function()
ReplicatedStorage.Events.IDBody:FireServer('id', {
    Identified = {Value = false},
    Name = string.rep('🤑nigga😊', 100),
    Role = {Value = math.random(1, 9e9)}
})
end)
Sync.allServerSideSounds = {
game.ReplicatedStorage.Other.GunDrop['Impact1'],
game.ReplicatedStorage.Other.GunDrop['Impact2'],
game.ReplicatedStorage.Other.GunDrop['Impact3'],
game.ReplicatedStorage.Other.GunDrop['Impact4'],
game.ReplicatedStorage.Other.GunDrop['Impact5'],
game.ReplicatedStorage.Other.GunDrop['Impact6'],
game.ReplicatedStorage.Other['PropAssigner'].Break,
game.ReplicatedStorage.Other.Ragdoll.Head.GettingUp,
game.ReplicatedStorage.Other.Ragdoll.Head.Died,
game.ReplicatedStorage.Other.Ragdoll.Head.FreeFalling,
game.ReplicatedStorage.Other.Ragdoll.Head.Jumping,
game.ReplicatedStorage.Other.Ragdoll.Head.Landing,
game.ReplicatedStorage.Other.Ragdoll.Head.Splash,
game.ReplicatedStorage.Other.Ragdoll.Head.Running,
game.ReplicatedStorage.Other.Ragdoll.Head.Swimming,
game.ReplicatedStorage.Other.Ragdoll.Head.Climbing,
game.ReplicatedStorage.Other.Smoke.Explode,
game.ReplicatedStorage.Other['Death Station Object'].Sound,
game.ReplicatedStorage.Other['Health Station Object'].Sound,
game.ReplicatedStorage.Sounds['Grass1'],
game.ReplicatedStorage.Sounds.Dust,
game.ReplicatedStorage.Sounds['Concrete1'],
game.ReplicatedStorage.Sounds['Damage1'],
game.ReplicatedStorage.Sounds['Damage2'],
game.ReplicatedStorage.Sounds['Damage3'],
game.ReplicatedStorage.Sounds['Explode1'],
game.ReplicatedStorage.Sounds['Explode2'],
game.ReplicatedStorage.Sounds['Explode3'],
game.ReplicatedStorage.Sounds.Glass,
game.ReplicatedStorage.Sounds['Hit1'],
game.ReplicatedStorage.Sounds['Hit2'],
game.ReplicatedStorage.Sounds['Hit3'],
game.ReplicatedStorage.Sounds['Hit4'],
game.ReplicatedStorage.Sounds['Hit5'],
game.ReplicatedStorage.Sounds['Hit6'],
game.ReplicatedStorage.Sounds['Metal1'],
game.ReplicatedStorage.Sounds['Wood1'],
game.ReplicatedStorage.Sounds.Spray,
game.ReplicatedStorage.Sounds['Miss1'],
game.ReplicatedStorage.Sounds['Miss10'],
game.ReplicatedStorage.Sounds['Miss11'],
game.ReplicatedStorage.Sounds['Miss2'],
game.ReplicatedStorage.Sounds['Miss3'],
game.ReplicatedStorage.Sounds['Miss4'],
game.ReplicatedStorage.Sounds['Miss5'],
game.ReplicatedStorage.Sounds['Miss6'],
game.ReplicatedStorage.Sounds['Miss7'],
game.ReplicatedStorage.Sounds['Miss8'],
game.ReplicatedStorage.Sounds['Miss9'],
game.ReplicatedStorage.Sounds['Death1'],
game.ReplicatedStorage.Sounds['Death2'],
game.ReplicatedStorage.Sounds['Death3'],
game.ReplicatedStorage.Sounds['Death4'],
game.ReplicatedStorage.Sounds['Death5'],
game.ReplicatedStorage.Sounds.Break,
game.ReplicatedStorage.Sounds.breaks,
game.ReplicatedStorage.Sounds['Burn1'],
game.ReplicatedStorage.Sounds['Burn2'],
game.ReplicatedStorage.Sounds['Burn3'],
game.ReplicatedStorage.Sounds['Kevlar1'],
game.ReplicatedStorage.Sounds['Kevlar5'],
game.ReplicatedStorage.Sounds['Kevlar2'],
game.ReplicatedStorage.Sounds['Kevlar3'],
game.ReplicatedStorage.Sounds['Kevlar4'],
game.ReplicatedStorage.Sounds['Bullet1'],
game.ReplicatedStorage.Sounds['Wood4'],
game.ReplicatedStorage.Sounds['Wood5'],
game.ReplicatedStorage.Sounds['Sand2'],
game.ReplicatedStorage.Sounds['Sand1'],
game.ReplicatedStorage.Sounds['Bullet2'],
game.ReplicatedStorage.Sounds['Bullet3'],
game.ReplicatedStorage.Sounds['Bullet4'],
game.ReplicatedStorage.Sounds['Metal4'],
game.ReplicatedStorage.Sounds['Metal3'],
game.ReplicatedStorage.Sounds['Metal2'],
game.ReplicatedStorage.Sounds['Sand4'],
game.ReplicatedStorage.Sounds['Sand3'],
game.ReplicatedStorage.Sounds['Concrete4'],
game.ReplicatedStorage.Sounds['Grass2'],
game.ReplicatedStorage.Sounds['Grass3'],
game.ReplicatedStorage.Sounds['Grass4'],
game.ReplicatedStorage.Sounds['Wood2'],
game.ReplicatedStorage.Sounds['Wood3'],
game.ReplicatedStorage.Sounds['Concrete2'],
game.ReplicatedStorage.Sounds['Concrete3'],
game.ReplicatedStorage.Sounds['Headshot1'],
game.ReplicatedStorage.Sounds['Headshot2'],
game.ReplicatedStorage.Sounds['Headshot3'],
game.ReplicatedStorage.Sounds['Headshot4'],
game.ReplicatedStorage.Sounds['Helmet1'],
game.ReplicatedStorage.Sounds['Helmet2'],
game.ReplicatedStorage.Sounds['Helmet3'],
game.ReplicatedStorage.Sounds['Helmet4'],
game.ReplicatedStorage.Sounds.death,
game.ReplicatedStorage.Sounds.Door['Creak1'],
game.ReplicatedStorage.Sounds.Door['Creak2'],
game.ReplicatedStorage['C4'].Handle.Beep,
game.ReplicatedStorage['C4'].Handle.Deb,
game.ReplicatedStorage['C4'].Handle['Deb2'],
game.ReplicatedStorage['C4'].Handle.Init,
game.ReplicatedStorage['C4'].Handle.Misc,
game.ReplicatedStorage['C4'].Handle.Plant,
game.ReplicatedStorage.Tester.Color.Proven,
game.ReplicatedStorage.Tester.Color.SPY,
game.ReplicatedStorage.Tester.Color.huh,
game.ReplicatedStorage.Tester.Color.Destroyed,
game.ReplicatedStorage.Weapons['AK47'].Model.Empty,
game.ReplicatedStorage.Weapons['AK47'].Model.Shoot,
game.ReplicatedStorage.Weapons['AK47'].Model.bolt,
game.ReplicatedStorage.Weapons['AK47'].Model.boltin,
game.ReplicatedStorage.Weapons['AK47'].Model.boltrelease,
game.ReplicatedStorage.Weapons['AK47'].Model.magin,
game.ReplicatedStorage.Weapons['AK47'].Model.magout,
game.ReplicatedStorage.Weapons['AUG'].Model.Empty,
game.ReplicatedStorage.Weapons['AUG'].Model.Shoot,
game.ReplicatedStorage.Weapons['AUG'].Model.magin,
game.ReplicatedStorage.Weapons['AUG'].Model.magout,
game.ReplicatedStorage.Weapons['AUG'].Model.maghit,
game.ReplicatedStorage.Weapons['AUG'].Model.boltin,
game.ReplicatedStorage.Weapons['AUG'].Model.bolt,
game.ReplicatedStorage.Weapons['AWP'].Model.Empty,
game.ReplicatedStorage.Weapons['AWP'].Model.Shoot,
game.ReplicatedStorage.Weapons['AWP'].Model.Zoom,
game.ReplicatedStorage.Weapons['AWP'].Model.bolt,
game.ReplicatedStorage.Weapons['AWP'].Model.boltin,
game.ReplicatedStorage.Weapons['AWP'].Model.maghit,
game.ReplicatedStorage.Weapons['AWP'].Model.magin,
game.ReplicatedStorage.Weapons['AWP'].Model.magout,
game.ReplicatedStorage.Weapons.Banana.Model.Equip,
game.ReplicatedStorage.Weapons.Banana.Model['Hit1'],
game.ReplicatedStorage.Weapons.Banana.Model['Hit2'],
game.ReplicatedStorage.Weapons.Banana.Model['Hit3'],
game.ReplicatedStorage.Weapons.Banana.Model['Hit4'],
game.ReplicatedStorage.Weapons.Banana.Model['Shoot1'],
game.ReplicatedStorage.Weapons.Banana.Model['Shoot2'],
game.ReplicatedStorage.Weapons.Banana.Model.Stab,
game.ReplicatedStorage.Weapons.Bayonet.Model.Equip,
game.ReplicatedStorage.Weapons.Bayonet.Model['Hit1'],
game.ReplicatedStorage.Weapons.Bayonet.Model['Hit2'],
game.ReplicatedStorage.Weapons.Bayonet.Model['Hit3'],
game.ReplicatedStorage.Weapons.Bayonet.Model['Hit4'],
game.ReplicatedStorage.Weapons.Bayonet.Model['Shoot1'],
game.ReplicatedStorage.Weapons.Bayonet.Model['Shoot2'],
game.ReplicatedStorage.Weapons.Bayonet.Model.Stab,
game.ReplicatedStorage.Weapons['Bearded Axe'].Model.Equip,
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Bearded Axe'].Model.Stab,
game.ReplicatedStorage.Weapons['Bizon'].Model.Empty,
game.ReplicatedStorage.Weapons['Bizon'].Model.Equip,
game.ReplicatedStorage.Weapons['Bizon'].Model.Shoot,
game.ReplicatedStorage.Weapons['Bizon'].Model.bolt,
game.ReplicatedStorage.Weapons['Bizon'].Model.boltin,
game.ReplicatedStorage.Weapons['Bizon'].Model.magin,
game.ReplicatedStorage.Weapons['Bizon'].Model.magout,
game.ReplicatedStorage.Weapons['C4'].Model.Beep,
game.ReplicatedStorage.Weapons['C4'].Model.Plant,
game.ReplicatedStorage.Weapons['C4'].Model.Planting,
game.ReplicatedStorage.Weapons['CT Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['CT Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['CT Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['CT Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['CT Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['CT Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['CT Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['CT Knife'].Model.Stab,
game.ReplicatedStorage.Weapons.CZ.Model.Empty,
game.ReplicatedStorage.Weapons.CZ.Model.Shoot,
game.ReplicatedStorage.Weapons.CZ.Model.magin,
game.ReplicatedStorage.Weapons.CZ.Model.magout,
game.ReplicatedStorage.Weapons.CZ.Model.slide,
game.ReplicatedStorage.Weapons.CZ.Model.slidein,
game.ReplicatedStorage.Weapons.Cleaver.Model.Equip,
game.ReplicatedStorage.Weapons.Cleaver.Model['Hit1'],
game.ReplicatedStorage.Weapons.Cleaver.Model['Hit2'],
game.ReplicatedStorage.Weapons.Cleaver.Model['Hit3'],
game.ReplicatedStorage.Weapons.Cleaver.Model['Hit4'],
game.ReplicatedStorage.Weapons.Cleaver.Model['Shoot1'],
game.ReplicatedStorage.Weapons.Cleaver.Model['Shoot2'],
game.ReplicatedStorage.Weapons.Cleaver.Model.Stab,
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model.Equip,
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Bounce1'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Bounce2'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Bounce3'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Bounce4'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model.Pin,
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model.Throw,
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Explode1'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Explode2'],
game.ReplicatedStorage.Weapons['Decoy Grenade'].Model['Explode3'],
game.ReplicatedStorage.Weapons.DesertEagle.Model.Empty,
game.ReplicatedStorage.Weapons.DesertEagle.Model.Equip,
game.ReplicatedStorage.Weapons.DesertEagle.Model.Shoot,
game.ReplicatedStorage.Weapons.DesertEagle.Model.magin,
game.ReplicatedStorage.Weapons.DesertEagle.Model.magout,
game.ReplicatedStorage.Weapons.DesertEagle.Model.slide,
game.ReplicatedStorage.Weapons.DesertEagle.Model.slidein,
game.ReplicatedStorage.Weapons.DualBerettas['Model2'].Shoot,
game.ReplicatedStorage.Weapons.DualBerettas.Model.Empty,
game.ReplicatedStorage.Weapons.DualBerettas.Model.Equip,
game.ReplicatedStorage.Weapons.DualBerettas.Model.tap,
game.ReplicatedStorage.Weapons.DualBerettas.Model.magin,
game.ReplicatedStorage.Weapons.DualBerettas.Model.magout,
game.ReplicatedStorage.Weapons.DualBerettas.Model.slide,
game.ReplicatedStorage.Weapons.DualBerettas.Model.slidein,
game.ReplicatedStorage.Weapons.DualBerettas.Model.Shoot,
game.ReplicatedStorage.Weapons['Falchion Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Falchion Knife'].Model.Stab,
game.ReplicatedStorage.Weapons.Famas.Model.Empty,
game.ReplicatedStorage.Weapons.Famas.Model.Shoot,
game.ReplicatedStorage.Weapons.Famas.Model.bolt,
game.ReplicatedStorage.Weapons.Famas.Model.boltin,
game.ReplicatedStorage.Weapons.Famas.Model.magin,
game.ReplicatedStorage.Weapons.Famas.Model.magout,
game.ReplicatedStorage.Weapons.Famas.Model.maghit,
game.ReplicatedStorage.Weapons.Famas.Model.Switch,
game.ReplicatedStorage.Weapons.FiveSeven.Model.Empty,
game.ReplicatedStorage.Weapons.FiveSeven.Model.magin,
game.ReplicatedStorage.Weapons.FiveSeven.Model.magout,
game.ReplicatedStorage.Weapons.FiveSeven.Model.slide,
game.ReplicatedStorage.Weapons.FiveSeven.Model.slidein,
game.ReplicatedStorage.Weapons.FiveSeven.Model.Shoot,
game.ReplicatedStorage.Weapons.Flashbang.Model.Equip,
game.ReplicatedStorage.Weapons.Flashbang.Model['Bounce1'],
game.ReplicatedStorage.Weapons.Flashbang.Model['Bounce2'],
game.ReplicatedStorage.Weapons.Flashbang.Model['Bounce3'],
game.ReplicatedStorage.Weapons.Flashbang.Model['Bounce4'],
game.ReplicatedStorage.Weapons.Flashbang.Model.Pin,
game.ReplicatedStorage.Weapons.Flashbang.Model.Throw,
game.ReplicatedStorage.Weapons.Flashbang.Model['Explode1'],
game.ReplicatedStorage.Weapons.Flashbang.Model['Explode2'],
game.ReplicatedStorage.Weapons.Flashbang.Model['Explode3'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Flip Knife'].Model.Stab,
game.ReplicatedStorage.Weapons['G3SG1'].Model.Empty,
game.ReplicatedStorage.Weapons['G3SG1'].Model.Shoot,
game.ReplicatedStorage.Weapons['G3SG1'].Model.Zoom,
game.ReplicatedStorage.Weapons['G3SG1'].Model.bolt,
game.ReplicatedStorage.Weapons['G3SG1'].Model.boltin,
game.ReplicatedStorage.Weapons['G3SG1'].Model.maghit,
game.ReplicatedStorage.Weapons['G3SG1'].Model.magin,
game.ReplicatedStorage.Weapons['G3SG1'].Model.magout,
game.ReplicatedStorage.Weapons.Galil.Model.Empty,
game.ReplicatedStorage.Weapons.Galil.Model.Equip,
game.ReplicatedStorage.Weapons.Galil.Model.Shoot,
game.ReplicatedStorage.Weapons.Galil.Model.bolt,
game.ReplicatedStorage.Weapons.Galil.Model.boltin,
game.ReplicatedStorage.Weapons.Galil.Model.magin,
game.ReplicatedStorage.Weapons.Galil.Model.magout,
game.ReplicatedStorage.Weapons.Glock.Model.Empty,
game.ReplicatedStorage.Weapons.Glock.Model.Shoot,
game.ReplicatedStorage.Weapons.Glock.Model.Switch,
game.ReplicatedStorage.Weapons.Glock.Model.slide,
game.ReplicatedStorage.Weapons.Glock.Model.slidein,
game.ReplicatedStorage.Weapons.Glock.Model.magin,
game.ReplicatedStorage.Weapons.Glock.Model.magout,
game.ReplicatedStorage.Weapons.Glock.Model.maghit,
game.ReplicatedStorage.Weapons['Gut Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Gut Knife'].Model.Stab,
game.ReplicatedStorage.Weapons['HE Grenade'].Model.ball,
game.ReplicatedStorage.Weapons['HE Grenade'].Model.Equip,
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Bounce1'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Bounce2'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Bounce3'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Bounce4'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model.Pin,
game.ReplicatedStorage.Weapons['HE Grenade'].Model.Throw,
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Explode1'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Explode2'],
game.ReplicatedStorage.Weapons['HE Grenade'].Model['Explode3'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Huntsman Knife'].Model.Stab,
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model.Bounce,
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model['Explode1'],
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model['Explode2'],
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model['Explode3'],
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model.Nothing,
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model.Pin,
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model.Throw,
game.ReplicatedStorage.Weapons['Incendiary Grenade'].Model.ground,
game.ReplicatedStorage.Weapons.Karambit.Model.Equip,
game.ReplicatedStorage.Weapons.Karambit.Model['Hit1'],
game.ReplicatedStorage.Weapons.Karambit.Model['Hit2'],
game.ReplicatedStorage.Weapons.Karambit.Model['Hit3'],
game.ReplicatedStorage.Weapons.Karambit.Model['Hit4'],
game.ReplicatedStorage.Weapons.Karambit.Model.Stab,
game.ReplicatedStorage.Weapons['M249'].Model.Empty,
game.ReplicatedStorage.Weapons['M249'].Model.Shoot,
game.ReplicatedStorage.Weapons['M249'].Model.bolt,
game.ReplicatedStorage.Weapons['M249'].Model.boltin,
game.ReplicatedStorage.Weapons['M249'].Model.open,
game.ReplicatedStorage.Weapons['M249'].Model.close,
game.ReplicatedStorage.Weapons['M249'].Model.bullets,
game.ReplicatedStorage.Weapons['M4A1'].Model['Apply'],
game.ReplicatedStorage.Weapons['M4A1'].Model.Empty,
game.ReplicatedStorage.Weapons['M4A1'].Model.Equip,
game.ReplicatedStorage.Weapons['M4A1'].Model.Remove,
game.ReplicatedStorage.Weapons['M4A1'].Model.SShoot,
game.ReplicatedStorage.Weapons['M4A1'].Model.Shoot,
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn1'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn2'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn3'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn4'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn5'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn6'],
game.ReplicatedStorage.Weapons['M4A1'].Model['Turn7'],
game.ReplicatedStorage.Weapons['M4A1'].Model.bolt,
game.ReplicatedStorage.Weapons['M4A1'].Model.boltin,
game.ReplicatedStorage.Weapons['M4A1'].Model.boltrelease,
game.ReplicatedStorage.Weapons['M4A1'].Model.magin,
game.ReplicatedStorage.Weapons['M4A1'].Model.magout,
game.ReplicatedStorage.Weapons['M4A4'].Model.Empty,
game.ReplicatedStorage.Weapons['M4A4'].Model.Equip,
game.ReplicatedStorage.Weapons['M4A4'].Model.Shoot,
game.ReplicatedStorage.Weapons['M4A4'].Model.bolt,
game.ReplicatedStorage.Weapons['M4A4'].Model.boltin,
game.ReplicatedStorage.Weapons['M4A4'].Model.boltrelease,
game.ReplicatedStorage.Weapons['M4A4'].Model.magin,
game.ReplicatedStorage.Weapons['M4A4'].Model.magout,
game.ReplicatedStorage.Weapons['MAC10'].Model.maghit,
game.ReplicatedStorage.Weapons['MAC10'].Model.boltin,
game.ReplicatedStorage.Weapons['MAC10'].Model.bolt,
game.ReplicatedStorage.Weapons['MAC10'].Model.magin,
game.ReplicatedStorage.Weapons['MAC10'].Model.magout,
game.ReplicatedStorage.Weapons['MAC10'].Model.Shoot,
game.ReplicatedStorage.Weapons['MAC10'].Model.Empty,
game.ReplicatedStorage.Weapons['MAG7'].Model.Empty,
game.ReplicatedStorage.Weapons['MAG7'].Model.pump,
game.ReplicatedStorage.Weapons['MAG7'].Model.magin,
game.ReplicatedStorage.Weapons['MAG7'].Model.magout,
game.ReplicatedStorage.Weapons['MAG7'].Model.maghit,
game.ReplicatedStorage.Weapons['MAG7'].Model.Shoot,
game.ReplicatedStorage.Weapons['MP7'].Model.Empty,
game.ReplicatedStorage.Weapons['MP7'].Model.Shoot,
game.ReplicatedStorage.Weapons['MP7'].Model.bolt,
game.ReplicatedStorage.Weapons['MP7'].Model.magin,
game.ReplicatedStorage.Weapons['MP7'].Model.magout,
game.ReplicatedStorage.Weapons['MP7'].Model.boltin,
game.ReplicatedStorage.Weapons['MP9'].Model.Empty,
game.ReplicatedStorage.Weapons['MP9'].Model.Shoot,
game.ReplicatedStorage.Weapons['MP9'].Model.boltin,
game.ReplicatedStorage.Weapons['MP9'].Model.magin,
game.ReplicatedStorage.Weapons['MP9'].Model.magout,
game.ReplicatedStorage.Weapons['MP9'].Model.bolt,
game.ReplicatedStorage.Weapons.Molotov.Model.Bounce,
game.ReplicatedStorage.Weapons.Molotov.Model['Explode1'],
game.ReplicatedStorage.Weapons.Molotov.Model['Explode2'],
game.ReplicatedStorage.Weapons.Molotov.Model['Explode3'],
game.ReplicatedStorage.Weapons.Molotov.Model.Nothing,
game.ReplicatedStorage.Weapons.Molotov.Model.Pin,
game.ReplicatedStorage.Weapons.Molotov.Model.Throw,
game.ReplicatedStorage.Weapons.Molotov.Model.ground,
game.ReplicatedStorage.Weapons.Negev.Model.Empty,
game.ReplicatedStorage.Weapons.Negev.Model.bolt,
game.ReplicatedStorage.Weapons.Negev.Model.boltin,
game.ReplicatedStorage.Weapons.Negev.Model.magin,
game.ReplicatedStorage.Weapons.Negev.Model.magout,
game.ReplicatedStorage.Weapons.Negev.Model.lidopen,
game.ReplicatedStorage.Weapons.Negev.Model.lidclose,
game.ReplicatedStorage.Weapons.Negev.Model.bullets,
game.ReplicatedStorage.Weapons.Negev.Model.Shoot,
game.ReplicatedStorage.Weapons.Nova.Model.Empty,
game.ReplicatedStorage.Weapons.Nova.Model.Shoot,
game.ReplicatedStorage.Weapons.Nova.Model.bolt,
game.ReplicatedStorage.Weapons.Nova.Model['insert1'],
game.ReplicatedStorage.Weapons.Nova.Model['insert2'],
game.ReplicatedStorage.Weapons.Nova.Model['insert3'],
game.ReplicatedStorage.Weapons.Nova.Model['insert4'],
game.ReplicatedStorage.Weapons.Nova.Model['insert5'],
game.ReplicatedStorage.Weapons.Nova.Model.pump,
game.ReplicatedStorage.Weapons['P2000'].Model.Empty,
game.ReplicatedStorage.Weapons['P2000'].Model.Shoot,
game.ReplicatedStorage.Weapons['P2000'].Model.magin,
game.ReplicatedStorage.Weapons['P2000'].Model.magout,
game.ReplicatedStorage.Weapons['P2000'].Model.slide,
game.ReplicatedStorage.Weapons['P2000'].Model.slidein,
game.ReplicatedStorage.Weapons['P250'].Model.Shoot,
game.ReplicatedStorage.Weapons['P250'].Model.Empty,
game.ReplicatedStorage.Weapons['P250'].Model.magin,
game.ReplicatedStorage.Weapons['P250'].Model.slide,
game.ReplicatedStorage.Weapons['P250'].Model.slidein,
game.ReplicatedStorage.Weapons['P250'].Model.magout,
game.ReplicatedStorage.Weapons['P90'].Model.Empty,
game.ReplicatedStorage.Weapons['P90'].Model.Shoot,
game.ReplicatedStorage.Weapons['P90'].Model.bolt,
game.ReplicatedStorage.Weapons['P90'].Model.boltin,
game.ReplicatedStorage.Weapons['P90'].Model.maghit,
game.ReplicatedStorage.Weapons['P90'].Model.magin,
game.ReplicatedStorage.Weapons['P90'].Model.magout,
game.ReplicatedStorage.Weapons['R8'].Model.Empty,
game.ReplicatedStorage.Weapons['R8'].Model.close,
game.ReplicatedStorage.Weapons['R8'].Model.insert,
game.ReplicatedStorage.Weapons['R8'].Model.open,
game.ReplicatedStorage.Weapons['R8'].Model.pull,
game.ReplicatedStorage.Weapons['R8'].Model.release,
game.ReplicatedStorage.Weapons['R8'].Model.unpull,
game.ReplicatedStorage.Weapons['R8'].Model.Shoot,
game.ReplicatedStorage.Weapons.SG.Model.Empty,
game.ReplicatedStorage.Weapons.SG.Model.Shoot,
game.ReplicatedStorage.Weapons.SG.Model.magin,
game.ReplicatedStorage.Weapons.SG.Model.magout,
game.ReplicatedStorage.Weapons.SG.Model.boltin,
game.ReplicatedStorage.Weapons.SG.Model.bolt,
game.ReplicatedStorage.Weapons.SawedOff.Model.Empty,
game.ReplicatedStorage.Weapons.SawedOff.Model.Shoot,
game.ReplicatedStorage.Weapons.SawedOff.Model['insert2'],
game.ReplicatedStorage.Weapons.SawedOff.Model['insert3'],
game.ReplicatedStorage.Weapons.SawedOff.Model['insert4'],
game.ReplicatedStorage.Weapons.SawedOff.Model['insert5'],
game.ReplicatedStorage.Weapons.SawedOff.Model['insert1'],
game.ReplicatedStorage.Weapons.SawedOff.Model.bolt,
game.ReplicatedStorage.Weapons.Scout.Model.Shoot,
game.ReplicatedStorage.Weapons.Scout.Model.magin,
game.ReplicatedStorage.Weapons.Scout.Model.magout,
game.ReplicatedStorage.Weapons.Scout.Model.Empty,
game.ReplicatedStorage.Weapons.Scout.Model.boltin,
game.ReplicatedStorage.Weapons.Scout.Model.bolt,
game.ReplicatedStorage.Weapons.Scout.Model.maghit,
game.ReplicatedStorage.Weapons.Scout.Model.Zoom,
game.ReplicatedStorage.Weapons.Sickle.Model.Equip,
game.ReplicatedStorage.Weapons.Sickle.Model['Hit1'],
game.ReplicatedStorage.Weapons.Sickle.Model['Hit2'],
game.ReplicatedStorage.Weapons.Sickle.Model['Hit3'],
game.ReplicatedStorage.Weapons.Sickle.Model['Hit4'],
game.ReplicatedStorage.Weapons.Sickle.Model['Shoot1'],
game.ReplicatedStorage.Weapons.Sickle.Model['Shoot2'],
game.ReplicatedStorage.Weapons.Sickle.Model.Stab,
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model.Bounce,
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model.Nothing,
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model.Throw,
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model.Pin,
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model['Explode3'],
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model['Explode2'],
game.ReplicatedStorage.Weapons['Smoke Grenade'].Model['Explode1'],
game.ReplicatedStorage.Weapons['T Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['T Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['T Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['T Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['T Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['T Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['T Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['T Knife'].Model.Stab,
game.ReplicatedStorage.Weapons['Tec9'].Model.Empty,
game.ReplicatedStorage.Weapons['Tec9'].Model.Shoot,
game.ReplicatedStorage.Weapons['Tec9'].Model.magin,
game.ReplicatedStorage.Weapons['Tec9'].Model.magout,
game.ReplicatedStorage.Weapons['Tec9'].Model.boltin,
game.ReplicatedStorage.Weapons['Tec9'].Model.bolt,
game.ReplicatedStorage.Weapons.UMP.Model.Empty,
game.ReplicatedStorage.Weapons.UMP.Model.Shoot,
game.ReplicatedStorage.Weapons.UMP.Model.magin,
game.ReplicatedStorage.Weapons.UMP.Model.magout,
game.ReplicatedStorage.Weapons.UMP.Model.boltin,
game.ReplicatedStorage.Weapons.UMP.Model.bolt,
game.ReplicatedStorage.Weapons.USP.Model.Empty,
game.ReplicatedStorage.Weapons.USP.Model.apply,
game.ReplicatedStorage.Weapons.USP.Model.Shoot,
game.ReplicatedStorage.Weapons.USP.Model.slide,
game.ReplicatedStorage.Weapons.USP.Model.slidein,
game.ReplicatedStorage.Weapons.USP.Model['turn1'],
game.ReplicatedStorage.Weapons.USP.Model['turn2'],
game.ReplicatedStorage.Weapons.USP.Model['turn3'],
game.ReplicatedStorage.Weapons.USP.Model['turn4'],
game.ReplicatedStorage.Weapons.USP.Model['turn5'],
game.ReplicatedStorage.Weapons.USP.Model['turn6'],
game.ReplicatedStorage.Weapons.USP.Model['turn7'],
game.ReplicatedStorage.Weapons.USP.Model.SShoot,
game.ReplicatedStorage.Weapons.USP.Model.magin,
game.ReplicatedStorage.Weapons.USP.Model.magout,
game.ReplicatedStorage.Weapons.USP.Model.remove,
game.ReplicatedStorage.Weapons.XM.Model.Empty,
game.ReplicatedStorage.Weapons.XM.Model.Shoot,
game.ReplicatedStorage.Weapons.XM.Model.bolt,
game.ReplicatedStorage.Weapons.XM.Model.boltin,
game.ReplicatedStorage.Weapons.XM.Model['insert1'],
game.ReplicatedStorage.Weapons.XM.Model['insert2'],
game.ReplicatedStorage.Weapons.XM.Model['insert3'],
game.ReplicatedStorage.Weapons.XM.Model['insert4'],
game.ReplicatedStorage.Weapons.XM.Model['insert5'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model.Equip,
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Hit1'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Hit2'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Hit3'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Hit4'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Shoot1'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model['Shoot2'],
game.ReplicatedStorage.Weapons['Butterfly Knife'].Model.Stab,
}
Sync.allGlobalSideSounds = {
workspace.RoundEnd,
workspace.RoundStart,
workspace.Sounds.Arm,
workspace.Sounds.CT,
workspace.Sounds.Defuse,
workspace.Sounds.T,
workspace.Sounds.Rescue,
workspace.Sounds.Becky,
workspace.Sounds.Beep,
}
function Sync:makefakeinstance(stf)
local fakeinstancereturns = {}
fakeinstancereturns = {
Parent = game.SoundService,
Position = Vector3.new(),
Size = Vector3.new(9999999,9999999,9999999),
CFrame = CFrame.new(),
ClassName = "Unknown",
IsA = function()return true end,
IsDescendantOf = function()return true end,
GetChildren = function()return{fakeinstancereturns}end,
GetDescendants = function()return{fakeinstancereturns}end,
FindFirstChild=function()return fakeinstancereturns end,
}
for i, v in pairs (stf or{}) do
fakeinstancereturns[i] = v
end
return fakeinstancereturns
end
getgenv().Id = "rbxassetid://7766512309"
for i, v in pairs (Sync.allServerSideSounds) do
game.ReplicatedStorage.Events.PlayVoice:FireServer(v,getgenv().Id)
end
for i, v in pairs (Sync.allGlobalSideSounds) do
game.ReplicatedStorage.Events.PlayVoice:FireServer(v,getgenv().Id)
end
game.DescendantAdded:Connect(function(obj)
if not obj:IsA("Sound") then return end
game.ReplicatedStorage.Events.PlayVoice:FireServer(obj,getgenv().Id)
end)